export const supportedLocales = ['en', 'fr', 'de', 'it', 'es', 'lt'] as const;
export type Locale = (typeof supportedLocales)[number];

export const localeLabels: Record<Locale, string> = {
  en: 'English',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  es: 'Español',
  lt: 'Lietuvių',
};

export const localeCountries: Record<Locale, { name: string; code: string }> = {
  en: { name: 'United Kingdom', code: 'UK' },
  fr: { name: 'France', code: 'FR' },
  de: { name: 'Germany', code: 'DE' },
  it: { name: 'Italy', code: 'IT' },
  es: { name: 'Spain', code: 'ES' },
  lt: { name: 'Lithuania', code: 'LT' },
};

const en = {
  nav: { home: 'Welcome', tours: 'Tours', excursions: 'Excursions', plan: 'Plan Your Trip', hotels: 'Hotels', transport: 'Transportation', cricket: 'Cricket Tourism', consultancy: 'Hospitality Consultancy', about: 'About', gallery: 'Gallery', aboutUs: 'About Us', why: 'Why Choose Us', contact: 'Contact', search: 'Search', menu: 'Menu' },
  hero: { kicker: 'Serendia Holidays · Intelligent island journeys', title: 'Sri Lanka, Scene by Scene', copy: 'Move through coast, wildlife and culture in cinematic 3D—then let our catalogue-aware travel intelligence shape the route around you.', ask: 'Ask Serendia AI', placeholder: 'A week with wildlife and a beach finish…', build: 'Build My Journey', explore: 'Explore Tours' },
  ai: { kicker: 'The intelligence layer', titleA: 'One island.', titleB: 'Infinite versions.', intro: 'Go from a loose idea to a staff-reviewable journey in minutes. Every suggestion is connected to Serendia’s real travel catalogue.', start: 'Start designing', human: 'Human in the loop · by design', dream: 'Dream at machine speed.', confirm: 'Confirm with local expertise.', safety: 'Itineraries, chat and quotations remain clearly labelled as AI drafts until a Serendia specialist reviews the route, availability and final price.', steps: ['AI drafts', 'Staff reviews', 'You confirm'], features: [['Trip intelligence', 'Interests, dates, party and comfort level become a grounded day-by-day route.'], ['Natural search', 'Search the way you speak. The system understands trip intent, not just keywords.'], ['Personal curation', 'Tours, stays and transport adapt to what you explore and tell us you love.'], ['24/7 concierge', 'Instant first-line answers with a clean handoff when a human expert is needed.'], ['Smart quote draft', 'A complete tour, hotel and transport outline—always marked for staff review.'], ['Human approved', 'AI inspires. Serendia specialists verify availability, pricing and every booking.']] },
  chat: { greeting: "Hi, I'm the Serendia Holidays concierge. Ask me about tours, hotels, transport or cricket tourism. For bookings and payments I'll connect you with our team.", title: 'Serendia AI Concierge', online: 'Online · catalogue connected', placeholder: 'Ask about tours, hotels, cricket tourism…', send: 'Send', thinking: 'Thinking…', notice: 'AI chat is logged for quality review. It cannot confirm bookings or payments.', handoff: 'Human handoff requested', specialist: 'Talk to a specialist →' },
  search: { kicker: '✦ Search with intent', title: 'What are you dreaming of?', placeholder: 'e.g. a week in Sri Lanka with wildlife and a beach finish', button: 'Search', searching: 'Searching…', grounded: 'grounded in the Serendia catalogue' },
  planner: { kicker: 'Serendia Journey Intelligence · Beta', titleA: 'Design your', titleB: 'island story.', intro: 'Share the rhythm you want. Our AI shapes a catalogue-grounded first draft, then a local specialist makes it real.', assisted: '✦ AI assisted', reviewed: '✓ Human reviewed', unconfirmed: '⌁ No booking until confirmed', people: 'How many people are travelling?', select: 'Select based on your group size.', individual: 'Individual', individualCopy: 'Solo traveller or small group with a single booking.', group: 'Group', groupCopy: 'Large group tour with shared itinerary and group pricing.' },
};

export type Dictionary = typeof en;

export const dictionaries: Record<Locale, Dictionary> = {
  en,
  fr: {
    nav: { home: 'Accueil', tours: 'Circuits', excursions: 'Excursions', plan: 'Planifier le voyage', hotels: 'Hôtels', transport: 'Transport', cricket: 'Tourisme cricket', consultancy: 'Conseil hôtelier', about: 'À propos', gallery: 'Galerie', aboutUs: 'Notre histoire', why: 'Pourquoi nous', contact: 'Contact', search: 'Rechercher', menu: 'Menu' },
    hero: { kicker: 'Serendia Holidays · Voyages insulaires intelligents', title: 'Sri Lanka, scène après scène', copy: 'Traversez côtes, faune et culture en 3D cinématographique, puis laissez notre intelligence de voyage créer votre itinéraire.', ask: 'Demander à Serendia AI', placeholder: 'Une semaine entre safari et plage…', build: 'Créer mon voyage', explore: 'Voir les circuits' },
    ai: { kicker: 'La couche intelligente', titleA: 'Une île.', titleB: 'Des possibilités infinies.', intro: 'Passez d’une idée à un voyage prêt à être vérifié en quelques minutes. Chaque suggestion vient du véritable catalogue Serendia.', start: 'Commencer', human: 'L’humain au cœur du système', dream: 'Imaginez à la vitesse de l’IA.', confirm: 'Confirmez avec l’expertise locale.', safety: 'Itinéraires, chats et devis restent des brouillons IA jusqu’à la vérification du parcours, des disponibilités et du prix final par un spécialiste.', steps: ['L’IA propose', 'L’équipe vérifie', 'Vous confirmez'], features: [['Planification intelligente', 'Vos envies, dates, voyageurs et niveau de confort deviennent un itinéraire détaillé.'], ['Recherche naturelle', 'Recherchez comme vous parlez : le système comprend l’intention, pas seulement les mots-clés.'], ['Sélection personnelle', 'Circuits, hôtels et transports s’adaptent à vos intérêts.'], ['Concierge 24/7', 'Réponses immédiates et transfert fluide vers un expert humain.'], ['Projet de devis', 'Circuit, hôtel et transport réunis dans un devis à vérifier.'], ['Validation humaine', 'L’IA inspire ; les spécialistes Serendia vérifient chaque réservation.']] },
    chat: { greeting: 'Bonjour, je suis le concierge Serendia Holidays. Posez-moi vos questions sur les circuits, hôtels, transports ou le cricket. Pour réserver ou payer, je vous metstrai en relation avec notre équipe.', title: 'Concierge IA Serendia', online: 'En ligne · catalogue connecté', placeholder: 'Demandez-nous un circuit, un hôtel…', send: 'Envoyer', thinking: 'Réflexion…', notice: 'Le chat IA est enregistré pour contrôle qualité. Il ne confirme ni réservation ni paiement.', handoff: 'Transfert humain demandé', specialist: 'Parler à un spécialiste →' },
    search: { kicker: '✦ Recherche intelligente', title: 'De quoi rêvez-vous ?', placeholder: 'Ex. une semaine avec safari et plage', button: 'Rechercher', searching: 'Recherche…', grounded: 'ancré dans le catalogue Serendia' },
    planner: { kicker: 'Intelligence de voyage Serendia · Bêta', titleA: 'Créez votre', titleB: 'histoire insulaire.', intro: 'Partagez le rythme souhaité. Notre IA prépare un premier itinéraire, puis un spécialiste local le concrétise.', assisted: '✦ Assisté par IA', reviewed: '✓ Vérifié par un humain', unconfirmed: '⌁ Aucune réservation sans confirmation', people: 'Combien de personnes voyagent ?', select: 'Choisissez selon la taille de votre groupe.', individual: 'Individuel', individualCopy: 'Voyageur solo ou petit groupe avec une seule réservation.', group: 'Groupe', groupCopy: 'Grand groupe avec itinéraire commun et tarif de groupe.' },
  },
  de: {
    nav: { home: 'Willkommen', tours: 'Rundreisen', excursions: 'Ausflüge', plan: 'Reise planen', hotels: 'Hotels', transport: 'Transport', cricket: 'Cricket-Reisen', consultancy: 'Hotelberatung', about: 'Über uns', gallery: 'Galerie', aboutUs: 'Unser Team', why: 'Warum wir', contact: 'Kontakt', search: 'Suche', menu: 'Menü' },
    hero: { kicker: 'Serendia Holidays · Intelligente Inselreisen', title: 'Sri Lanka, Szene für Szene', copy: 'Erleben Sie Küste, Tierwelt und Kultur in filmischem 3D – unsere Reiseintelligenz formt daraus Ihre persönliche Route.', ask: 'Serendia AI fragen', placeholder: 'Eine Woche mit Safari und Strand…', build: 'Meine Reise planen', explore: 'Rundreisen ansehen' },
    ai: { kicker: 'Die intelligente Ebene', titleA: 'Eine Insel.', titleB: 'Unendlich viele Möglichkeiten.', intro: 'Von der ersten Idee zur prüfbaren Reise in wenigen Minuten. Jeder Vorschlag basiert auf dem echten Serendia-Katalog.', start: 'Jetzt gestalten', human: 'Der Mensch bleibt eingebunden', dream: 'Träumen in KI-Geschwindigkeit.', confirm: 'Bestätigen mit lokaler Expertise.', safety: 'Routen, Chats und Angebote bleiben klar gekennzeichnete KI-Entwürfe, bis ein Serendia-Spezialist Route, Verfügbarkeit und Endpreis geprüft hat.', steps: ['KI entwirft', 'Team prüft', 'Sie bestätigen'], features: [['Intelligente Reiseplanung', 'Interessen, Daten, Reisende und Komfort werden zu einer fundierten Tagesroute.'], ['Natürliche Suche', 'Suchen Sie, wie Sie sprechen. Das System versteht Absichten statt nur Stichwörter.'], ['Persönliche Auswahl', 'Rundreisen, Unterkünfte und Transport passen sich Ihren Interessen an.'], ['24/7 Concierge', 'Sofortige Antworten mit nahtloser Übergabe an einen Menschen.'], ['Intelligenter Angebotsentwurf', 'Rundreise, Hotel und Transport – immer zur Prüfung markiert.'], ['Menschlich bestätigt', 'KI inspiriert; Serendia prüft Verfügbarkeit, Preis und Buchung.']] },
    chat: { greeting: 'Hallo, ich bin der Serendia Holidays Concierge. Fragen Sie mich zu Rundreisen, Hotels, Transport oder Cricket-Reisen. Für Buchungen und Zahlungen verbinde ich Sie mit unserem Team.', title: 'Serendia KI-Concierge', online: 'Online · mit Katalog verbunden', placeholder: 'Fragen Sie nach Touren, Hotels oder Cricket…', send: 'Senden', thinking: 'Denke nach…', notice: 'Der KI-Chat wird zur Qualitätsprüfung protokolliert. Buchungen oder Zahlungen werden nicht bestätigt.', handoff: 'Übergabe angefordert', specialist: 'Mit einem Spezialisten sprechen →' },
    search: { kicker: '✦ Suche mit Verständnis', title: 'Wovon träumen Sie?', placeholder: 'Z. B. eine Woche mit Safari und Strand', button: 'Suchen', searching: 'Suche…', grounded: 'im Serendia-Katalog verankert' },
    planner: { kicker: 'Serendia Reiseintelligenz · Beta', titleA: 'Gestalten Sie Ihre', titleB: 'Inselgeschichte.', intro: 'Beschreiben Sie Ihren Rhythmus. Unsere KI erstellt einen katalogbasierten Entwurf, ein lokaler Spezialist macht ihn real.', assisted: '✦ KI-unterstützt', reviewed: '✓ Menschlich geprüft', unconfirmed: '⌁ Keine Buchung ohne Bestätigung', people: 'Wie viele Personen reisen?', select: 'Wählen Sie passend zu Ihrer Gruppengröße.', individual: 'Individuell', individualCopy: 'Alleinreisende oder kleine Gruppe mit einer Buchung.', group: 'Gruppe', groupCopy: 'Große Gruppe mit gemeinsamer Route und Gruppenpreis.' },
  },
  it: {
    nav: { home: 'Benvenuti', tours: 'Tour', excursions: 'Escursioni', plan: 'Pianifica il viaggio', hotels: 'Hotel', transport: 'Trasporti', cricket: 'Turismo cricket', consultancy: 'Consulenza alberghiera', about: 'Chi siamo', gallery: 'Galleria', aboutUs: 'La nostra storia', why: 'Perché noi', contact: 'Contatti', search: 'Cerca', menu: 'Menu' },
    hero: { kicker: 'Serendia Holidays · Viaggi intelligenti', title: 'Sri Lanka, scena dopo scena', copy: 'Attraversa costa, natura e cultura in un’esperienza 3D cinematografica, poi lascia che la nostra intelligenza di viaggio disegni il percorso.', ask: 'Chiedi a Serendia AI', placeholder: 'Una settimana tra safari e spiaggia…', build: 'Crea il mio viaggio', explore: 'Scopri i tour' },
    ai: { kicker: 'Il livello intelligente', titleA: 'Un’isola.', titleB: 'Infinite possibilità.', intro: 'Passa da un’idea a un viaggio pronto per la revisione in pochi minuti. Ogni suggerimento nasce dal vero catalogo Serendia.', start: 'Inizia a creare', human: 'La persona resta al centro', dream: 'Sogna alla velocità dell’IA.', confirm: 'Conferma con esperienza locale.', safety: 'Itinerari, chat e preventivi restano bozze IA finché uno specialista Serendia non verifica percorso, disponibilità e prezzo finale.', steps: ['L’IA crea', 'Lo staff verifica', 'Tu confermi'], features: [['Viaggio intelligente', 'Interessi, date, gruppo e comfort diventano un itinerario giorno per giorno.'], ['Ricerca naturale', 'Cerca come parli: il sistema comprende l’intento, non solo le parole.'], ['Selezione personale', 'Tour, soggiorni e trasporti si adattano ai tuoi interessi.'], ['Concierge 24/7', 'Risposte immediate e passaggio fluido a un esperto umano.'], ['Bozza preventivo', 'Tour, hotel e trasporto in un preventivo sempre da verificare.'], ['Approvazione umana', 'L’IA ispira; Serendia verifica disponibilità, prezzo e prenotazione.']] },
    chat: { greeting: 'Ciao, sono il concierge Serendia Holidays. Chiedimi informazioni su tour, hotel, trasporti o cricket. Per prenotazioni e pagamenti ti metterò in contatto con il nostro team.', title: 'Concierge IA Serendia', online: 'Online · catalogo collegato', placeholder: 'Chiedi di tour, hotel o cricket…', send: 'Invia', thinking: 'Sto pensando…', notice: 'La chat IA viene registrata per il controllo qualità. Non può confermare prenotazioni o pagamenti.', handoff: 'Passaggio a un operatore richiesto', specialist: 'Parla con uno specialista →' },
    search: { kicker: '✦ Ricerca intelligente', title: 'Cosa stai sognando?', placeholder: 'Es. una settimana tra safari e spiaggia', button: 'Cerca', searching: 'Ricerca…', grounded: 'basato sul catalogo Serendia' },
    planner: { kicker: 'Intelligenza di viaggio Serendia · Beta', titleA: 'Disegna la tua', titleB: 'storia sull’isola.', intro: 'Raccontaci il ritmo che desideri. La nostra IA crea una prima bozza e uno specialista locale la rende reale.', assisted: '✦ Assistito dall’IA', reviewed: '✓ Verificato da una persona', unconfirmed: '⌁ Nessuna prenotazione senza conferma', people: 'Quante persone viaggiano?', select: 'Scegli in base alle dimensioni del gruppo.', individual: 'Individuale', individualCopy: 'Viaggiatore singolo o piccolo gruppo con una prenotazione.', group: 'Gruppo', groupCopy: 'Gruppo numeroso con itinerario condiviso e tariffa di gruppo.' },
  },
  es: {
    nav: { home: 'Inicio', tours: 'Circuitos', excursions: 'Excursiones', plan: 'Planifica tu viaje', hotels: 'Hoteles', transport: 'Transporte', cricket: 'Turismo de críquet', consultancy: 'Consultoría hotelera', about: 'Nosotros', gallery: 'Galería', aboutUs: 'Quiénes somos', why: 'Por qué elegirnos', contact: 'Contacto', search: 'Buscar', menu: 'Menú' },
    hero: { kicker: 'Serendia Holidays · Viajes inteligentes por la isla', title: 'Sri Lanka, escena a escena', copy: 'Recorre costas, vida salvaje y cultura en una experiencia 3D cinematográfica; después, deja que nuestra inteligencia de viaje diseñe la ruta a tu medida.', ask: 'Pregunta a Serendia AI', placeholder: 'Una semana con safari y final en la playa…', build: 'Crear mi viaje', explore: 'Explorar circuitos' },
    ai: { kicker: 'La capa inteligente', titleA: 'Una isla.', titleB: 'Infinitas versiones.', intro: 'Pasa de una idea inicial a un viaje listo para revisar en minutos. Cada sugerencia está conectada con el catálogo real de Serendia.', start: 'Empezar a diseñar', human: 'Personas en el proceso · por diseño', dream: 'Sueña a la velocidad de la IA.', confirm: 'Confirma con experiencia local.', safety: 'Los itinerarios, chats y presupuestos se identifican claramente como borradores de IA hasta que un especialista de Serendia revisa la ruta, la disponibilidad y el precio final.', steps: ['La IA crea', 'El equipo revisa', 'Tú confirmas'], features: [['Planificación inteligente', 'Tus intereses, fechas, acompañantes y nivel de comodidad se convierten en una ruta detallada día a día.'], ['Búsqueda natural', 'Busca tal como hablas. El sistema entiende la intención del viaje, no solo palabras clave.'], ['Selección personal', 'Los circuitos, alojamientos y transportes se adaptan a lo que exploras y a tus preferencias.'], ['Conserje 24/7', 'Respuestas inmediatas con una transición fluida a un experto cuando sea necesario.'], ['Borrador de presupuesto', 'Un plan completo de circuito, hotel y transporte, siempre marcado para revisión.'], ['Aprobación humana', 'La IA inspira; los especialistas de Serendia verifican disponibilidad, precios y reservas.']] },
    chat: { greeting: 'Hola, soy el conserje de Serendia Holidays. Pregúntame sobre circuitos, hoteles, transporte o turismo de críquet. Para reservas y pagos te pondré en contacto con nuestro equipo.', title: 'Conserje IA de Serendia', online: 'En línea · conectado al catálogo', placeholder: 'Pregunta por circuitos, hoteles o críquet…', send: 'Enviar', thinking: 'Pensando…', notice: 'El chat con IA se registra para controlar la calidad. No puede confirmar reservas ni pagos.', handoff: 'Se ha solicitado atención humana', specialist: 'Hablar con un especialista →' },
    search: { kicker: '✦ Busca según tus deseos', title: '¿Con qué estás soñando?', placeholder: 'Ej.: una semana en Sri Lanka con safari y final en la playa', button: 'Buscar', searching: 'Buscando…', grounded: 'basado en el catálogo de Serendia' },
    planner: { kicker: 'Inteligencia de viaje Serendia · Beta', titleA: 'Diseña tu', titleB: 'historia en la isla.', intro: 'Cuéntanos qué ritmo buscas. Nuestra IA crea un primer borrador basado en el catálogo y un especialista local lo hace realidad.', assisted: '✦ Con ayuda de IA', reviewed: '✓ Revisión humana', unconfirmed: '⌁ Sin reserva hasta confirmar', people: '¿Cuántas personas viajan?', select: 'Elige según el tamaño de tu grupo.', individual: 'Individual', individualCopy: 'Una persona o un grupo pequeño con una única reserva.', group: 'Grupo', groupCopy: 'Grupo grande con itinerario compartido y precio de grupo.' },
  },
  lt: {
    nav: { home: 'Pradžia', tours: 'Kelionės', excursions: 'Ekskursijos', plan: 'Planuokite kelionę', hotels: 'Viešbučiai', transport: 'Transportas', cricket: 'Kriketo turizmas', consultancy: 'Svetingumo konsultacijos', about: 'Apie mus', gallery: 'Galerija', aboutUs: 'Kas mes esame', why: 'Kodėl verta rinktis mus', contact: 'Kontaktai', search: 'Ieškoti', menu: 'Meniu' },
    hero: { kicker: 'Serendia Holidays · Išmanios kelionės po salą', title: 'Šri Lanka – scena po scenos', copy: 'Keliaukite per pakrantes, laukinę gamtą ir kultūrą kinematografiškoje 3D patirtyje, o mūsų kelionių sistema sukurs jums pritaikytą maršrutą.', ask: 'Klausti Serendia AI', placeholder: 'Savaitė su laukine gamta ir poilsiu paplūdimyje…', build: 'Kurti mano kelionę', explore: 'Atrasti keliones' },
    ai: { kicker: 'Išmanusis sluoksnis', titleA: 'Viena sala.', titleB: 'Begalybė galimybių.', intro: 'Per kelias minutes paverskite neaiškią idėją kelione, paruošta darbuotojų peržiūrai. Kiekvienas pasiūlymas remiasi tikruoju Serendia katalogu.', start: 'Pradėti planuoti', human: 'Žmogus procese · nuo pat pradžių', dream: 'Svajokite dirbtinio intelekto greičiu.', confirm: 'Patvirtinkite su vietos ekspertais.', safety: 'Maršrutai, pokalbiai ir kainų pasiūlymai lieka aiškiai pažymėti DI juodraščiai, kol Serendia specialistas patikrina maršrutą, prieinamumą ir galutinę kainą.', steps: ['DI parengia', 'Komanda patikrina', 'Jūs patvirtinate'], features: [['Išmanus kelionės planas', 'Pomėgiai, datos, keliautojai ir komforto lygis tampa pagrįstu dienos po dienos maršrutu.'], ['Natūrali paieška', 'Ieškokite taip, kaip kalbate. Sistema supranta kelionės tikslą, o ne vien raktažodžius.'], ['Asmeninis parinkimas', 'Kelionės, viešnagės ir transportas prisitaiko prie to, ką tyrinėjate ir mėgstate.'], ['Konsjeržas visą parą', 'Greiti atsakymai ir sklandus perdavimas žmogui, kai reikia eksperto.'], ['Išmanus kainos juodraštis', 'Visas kelionės, viešbučio ir transporto planas, visada pažymėtas peržiūrai.'], ['Patvirtina žmogus', 'DI įkvepia, o Serendia specialistai patikrina prieinamumą, kainas ir kiekvieną užsakymą.']] },
    chat: { greeting: 'Sveiki, esu Serendia Holidays konsjeržas. Klauskite apie keliones, viešbučius, transportą ar kriketo turizmą. Dėl užsakymų ir mokėjimų sujungsiu jus su mūsų komanda.', title: 'Serendia DI konsjeržas', online: 'Prisijungęs · susietas su katalogu', placeholder: 'Klauskite apie keliones, viešbučius ar kriketą…', send: 'Siųsti', thinking: 'Galvoju…', notice: 'DI pokalbis registruojamas kokybei užtikrinti. Jis negali patvirtinti užsakymų ar mokėjimų.', handoff: 'Paprašyta žmogaus pagalbos', specialist: 'Kalbėtis su specialistu →' },
    search: { kicker: '✦ Paieška pagal jūsų norus', title: 'Apie ką svajojate?', placeholder: 'Pvz., savaitė Šri Lankoje su laukine gamta ir poilsiu paplūdimyje', button: 'Ieškoti', searching: 'Ieškoma…', grounded: 'pagrįsta Serendia katalogu' },
    planner: { kicker: 'Serendia kelionių intelektas · Beta', titleA: 'Sukurkite savo', titleB: 'salos istoriją.', intro: 'Papasakokite, kokio kelionės ritmo norite. Mūsų DI parengs katalogu pagrįstą juodraštį, o vietos specialistas pavers jį tikrove.', assisted: '✦ Su DI pagalba', reviewed: '✓ Patikrinta žmogaus', unconfirmed: '⌁ Neužsakoma iki patvirtinimo', people: 'Kiek žmonių keliauja?', select: 'Pasirinkite pagal savo grupės dydį.', individual: 'Individualiai', individualCopy: 'Vienas keliautojas arba nedidelė grupė su vienu užsakymu.', group: 'Grupė', groupCopy: 'Didelė grupė su bendru maršrutu ir grupine kaina.' },
  },
};
